
<MyImage>:
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        Image:
            source: 'login.png'
            allow_stretch: True
            keep_ratio: True

            BoxLayout:
                orientation: 'vertical'
                size_hint_y: None
                height: dp(130)
                padding: dp(10)
                MDTextField:
                    id: username
                    hint_text: "Username"
                    size_hint_x: None
                    width: 300
                    font_size: '18sp'











