
<NewUser>:
    name: "NewUser"
    Screen:

        Image:
            source: 'newuser.png'
            size_hint: None, None
            width: "360"
            height: "640"
            pos_hint: {"center_x":0.5, "center_y":0.5}

          #---- image -----
        MDTextField:
            id: newname
            size_hint_x: None
            hint_text: "Name"
            width: 200
            font_size: '18sp'
            pos_hint: {"center_x":0.5, "center_y":0.68}


        MDTextField:
            id: newsurname
            size_hint_x: None
            hint_text: "Surname"
            width: 200
            font_size: '18sp'
            pos_hint: {"center_x":0.5, "center_y":0.61}
        MDTextField:
            hint_text: "Enter text here"

        MDTextField:
            id: newuser
            size_hint_x: None
            hint_text: "Username"
            width: 200
            font_size: '18sp'
            pos_hint: {"center_x":0.5, "center_y":0.54}

        MDTextField:
            id: newpass
            size_hint_x: None
            hint_text: "Password"
            password: True
            width: 200
            font_size: '18sp'
            pos_hint: {"center_x":0.5, "center_y":0.47}

        MDTextField:
            id: confirmpass
            size_hint_x: None
            hint_text: "Confirm Your Password"
            password: True
            width: 200
            font_size: '18sp'
            pos_hint: {"center_x":0.5, "center_y":0.4}

#-------------------------------------------- Button --------------------------------------------


        MDRectangleFlatButton:
            text: 'Create Account'
            size_hint: 0.5 , 0.01
            pos_hint: {'center_x': 0.5, 'center_y': 0.27}
            on_press: root.newacc()


        Button:
            text: "Already have an account?"
            font_size: 10
            color: "#63a9ff"
            pos_hint: {"center_x":0.35, "center_y":0.35}
            size_hint: 0.25, .01
            background_color: 0,0,0,0
            md_bg_color:  0,0,0,0
            on_press: root.manager.current = "login_screen"