<ForgotPassword>:
    name: "ForgotPassword"
    Screen:
        Image:
            source: 'kivy_gui/images/newuser.png'
            size_hint: None, None
            width: "360"
            height: "640"
            pos_hint: {"center_x":0.5, "center_y":0.5}

        Image:
            source: 'kivy_gui/images/mobile-app.png'
            size_hint: None, None
            width: "240"
            height: "128"
            pos_hint: {"center_x":0.5, "center_y":0.69}

        Label:
            id: error_label
            text: ""
            color: "#fc0303"
            pos_hint: {"center_x": 0.5, "center_y": 0.76}

        MDTextField:
            id: username
            size_hint_x: None
            hint_text: "Username"
            width: 200
            font_size: '18sp'
            pos_hint: {"center_x":0.5, "center_y":0.54}

        MDTextField:
            id: newpass
            size_hint_x: None
            hint_text: "Password"
            password: True
            width: 200
            font_size: '18sp'
            pos_hint: {"center_x":0.5, "center_y":0.47}

        MDTextField:
            id: confirmpass
            size_hint_x: None
            hint_text: "Confirm Your Password"
            password: True
            width: 200
            font_size: '18sp'
            pos_hint: {"center_x":0.5, "center_y":0.4}

#---------------------------------- Buttons -----------------------------

        MDRectangleFlatButton:
            text: 'Reset Password'
            size_hint: 0.5 , 0.01
            pos_hint: {'center_x': 0.5, 'center_y': 0.27}
            on_press: root.newpass()


        Button:
            text: "Go Back to Log In?"
            font_size: 10
            color: "#63a9ff"
            pos_hint: {"center_x":0.35, "center_y":0.35}
            size_hint: 0.25, .01
            background_color: 0,0,0,0
            md_bg_color:  0,0,0,0
            on_press: root.manager.current = "login_screen" 
