#:import ButtonBehavior kivy.uix.behaviors.ButtonBehavior
<Menu>:

    Image:
        source: 'kivy_gui/images/background.jpg'
        size_hint: 2,2
        pos_hint: {"center_x":0.5, "center_y":0.5}

    ScrollView:
        size_hint: 1, None
        height: self.parent.height
        

        BoxLayout:
            orientation:'vertical'
            size_hint_y: 2

            GridLayout:
                cols: 2     #add to colons 
                size_hint_y: 2  #increase the size 200%

                Button:         #profile picture
                    size_hint: 0.55, 1   #make x 60% of the widget
                    on_press: root.on_press()
                    background_color: 0,0,0,0
                    Image:
                        source: 'kivy_gui/images/profile.png'
                        center_x: self.parent.center_x
                        center_y: self.parent.center_y
                        allow_stretch: True

 
                BoxLayout:         
                    orientation: 'vertical'
                    padding: 5           
                    spacing: 5

                    Button:
                        text: "name: Lilly"
                        font_size: 20
                        color: 1 , 0 , 0 , 1
                        background_color: 0,0,0,0.4 

                    Button:
                        text: "Yonji"
                        font_size: 20
                        color: 1 , 0 , 0 , 1
                        background_color: 0,0,0,0.4


                    Button:
                        text: "Yutushi"
                        font_size: 20
                        color: 1 , 0 , 0 , 1
                        background_color: 0,0,0,0.4

            GridLayout:     #stats widget
                cols: 2
                size_hint_y: 2
                padding: 10
                spacing: 80

                BoxLayout:
                    orientation: 'vertical'
                    size_hint: 1 , 1
                    canvas:
                        Color:
                            rgba: 123, 172, 145, 0.3
                        Rectangle:
                            pos: self.pos
                            size:self.size

                    Button:
                        text:"Current Weight"
                        background_color: 0,0,0,0.4                        
                    Button:
                        text:"Weekly Goal"
                        background_color: 0,0,0,0.4 
                    Button:
                        text:"Goal Weight"
                        background_color: 0,0,0,0.4 
                    Button:
                        text:"Activment Level"
                        background_color: 0,0,0,0.4 

                BoxLayout:
                    orientation: 'vertical'
                    size_hint: 0.6 , 1
                    canvas:
                        Color:
                            rgba: 1, 5, 1, 0.3
                        Rectangle:
                            pos: self.pos
                            size:self.size
                    Button:
                        text:"5"
                        background_color: 0,0,0,0.4
                    Button:
                        text:"6"
                        background_color: 0,0,0,0.4
                    Button:
                        text:"7"
                        background_color: 0,0,0,0.4
                    Button:
                        text:"8"
                        background_color: 0,0,0,0.4

            Button: 
                text: "navigate"
                size_hint_y: 2
                

            Button: 
                text: "Graph"
                size_hint_y: 4

            Button: 
                text: "Average"
                size_hint_y: 2

