
#:include new_user.kv

WindowManager:
    Login:
    NewUser:

<Login>:
    name: 'login_screen'
    Screen:
        
        Image:
            source: 'images/login.png'
            size_hint: None, None
            size: root.width, root.height
            pos: root.x, root.y


        Label:
            id: error_label
            text: ""
            color: "#fc0303"
            pos_hint: {"center_x": 0.5, "center_y": 0.56}


        MDTextField:
            id: username
            hint_text: "Username"
            size_hint_x: None
            width: 200
            font_size: '18sp'
            pos_hint: {"center_x":0.5, "center_y":0.5}


        MDTextField:           # Password input field
            id: password
            size_hint_x: None
            hint_text: "Password"
            width: 200
            password: True
            font_size: '18sp'
            pos_hint: {"center_x":0.5, "center_y":0.4}

        MDRectangleFlatButton:   #log in button
            text: 'Log In'
            pos_hint: {'center_x': 0.7, 'center_y': 0.26}
            on_press: root.login()

        Button:
            id: forgotpassword
            text: "forgot Password"
            font_size: 10
            color: "#63a9ff"
            pos_hint: {"center_x":0.3, "center_y":0.35}
            size_hint: 0.23, .01
            background_color: 0,0,0,0
            md_bg_color:  0,0,0,0
            on_press: root.manager.current = "ForgotPassword"

        Button:
            id: newacc
            text:
                """
                Need a new
                account?
                """
            font_size: 12
            color: "#63a9ff"
            pos_hint: {"center_x":0.3, "center_y":0.29}
            size_hint: 0.2, .04
            background_color: 0,0,0,0
            md_bg_color: 0,0,0,0
            on_press: app.root.current = "NewUser"
