ScreenManager:
    LoginScreen:
    PassForgotSc:
    NewUser:

<LoginScreen>:
    Screen:
        name: "log"

        Image:
            source: 'login.png'
            size_hint: None, None
            width: "360"
            height: "640"
            pos_hint: {"center_x":0.5, "center_y":0.5}


        MDTextField:

            id: username
            hint_text: "Username"
            size_hint_x: None
            width: 200
            font_size: '18sp'
            pos_hint: {"center_x":0.5, "center_y":0.5}


        MDTextField:
            id: password

            size_hint_x: None
            hint_text: "Password"
            width: 200
            password: True
            font_size: '18sp'
            pos_hint: {"center_x":0.5, "center_y":0.4}



        MDRectangleFlatButton:
            text: 'Log In'
            pos_hint: {'center_x': 0.7, 'center_y': 0.26}
            on_press: root.login()

        Button:
            id: "forgotpassword"
            text: "forgot Password"
            font_size: 10
            color: "#63a9ff"
            pos_hint: {"center_x":0.3, "center_y":0.35}
            size_hint: 0.23, .01
            background_color: 0,0,0,0
            md_bg_color:  0,0,0,0
            on_press: root.manager.current = "PassForgot"

        Button:
            id: "newacc"
            text:
                """
                Need a new
                account?
                """
            font_size: 12
            color: "#63a9ff"
            pos_hint: {"center_x":0.3, "center_y":0.29}
            size_hint: 0.2, .04
            background_color: 0,0,0,0
            md_bg_color: 0,0,0,0
            on_press: root.manager.current = "newaccount"


#----------------------------------- resetting password screen -------------------------------


<PassForgotSc>:
    name: "PassForgot"
    Screen:

        Image:
            source: 'login.png'
            size_hint: None, None
            width: "360"
            height: "640"
            pos_hint: {"center_x":0.5, "center_y":0.5}


#---------------------------------- making new user account --------------------------

<NewUser>:
    name: "newaccount"
    Screen:

        Image:
            source: 'newuser.png'
            size_hint: None, None
            width: "360"
            height: "640"
            pos_hint: {"center_x":0.5, "center_y":0.5}

          #---- image -----
        MDTextField:
            id: "newname"
            size_hint_x: None
            hint_text: "Name"
            width: 200
            font_size: '18sp'
            pos_hint: {"center_x":0.5, "center_y":0.68}

        MDTextField:
            id: "newsurname"
            size_hint_x: None
            hint_text: "Surname"
            width: 200
            font_size: '18sp'
            pos_hint: {"center_x":0.5, "center_y":0.61}


        MDTextField:
            id: "newuser"
            size_hint_x: None
            hint_text: "Username"
            width: 200
            font_size: '18sp'
            pos_hint: {"center_x":0.5, "center_y":0.54}

        MDTextField:
            id: "newpass"
            size_hint_x: None
            hint_text: "Password"
            password: True
            width: 200
            font_size: '18sp'
            pos_hint: {"center_x":0.5, "center_y":0.47}

        MDTextField:
            id: "confirmpass"
            size_hint_x: None
            hint_text: "Confirm Your Password"
            password: True
            width: 200
            font_size: '18sp'
            pos_hint: {"center_x":0.5, "center_y":0.4}

        Button:
            id: "forgotpassword"
            text: "forgot Password"
            font_size: 10
            color: "#63a9ff"
            pos_hint: {"center_x":0.3, "center_y":0.35}
            size_hint: 0.23, .01
            background_color: 0,0,0,0
            md_bg_color:  0,0,0,0
            on_press: root.manager.current = "PassForgotSc"